### ISSUE TITLE
Notifications are set to "Alerts" by default

### ISSUE THREAD

**Issue by bressan3** [davicorreiajr/spotify-now-playing#26]
## What are you reporting?

* [ ] Notifications show up as Alerts instead of Banners after the App installation.

## In which context are you running the app?

OS: MacOS 10.14.2,
App version: 0.6.0

## Description

When running App and turning on the `Activate Notifications` option, notifications will show up as `Alerts` instead of `Banners` like they should. The App is automatically setting Spotify notifications as `Alerts` when it runs for the first time (even if they were set as `Banners` before). The only way to make the App display notifications like it should is to do it manually by going to `System Settings -> Notifications -> Spotify` and set `Spotify alert style` as `Banners`.

Notifications look like this by default...:

<img width="354" alt="screen shot 2019-01-11 at 12 03 05 am" src="https://user-images.githubusercontent.com/13811157/51008788-68aa8880-1534-11e9-9ce1-a3cd6753485a.png">

...But instead, they should look like this:

<img width="363" alt="screen shot 2019-01-11 at 12 02 45 am" src="https://user-images.githubusercontent.com/13811157/51008792-6d6f3c80-1534-11e9-9ebf-146ecbd9bb7a.png">

I've read some issue openings from both Terminal-Notifier and Node-Notifier's Github repos. Node-Notifier is used in this App and uses Terminal-Notifier do display notifications on MacOS. By doing so, I found a post saying that changing a certain parameter in a .plist file may solve this issue.

In this App's case, I found out this can be done by opening the file called `Info.plist` located under `spotify-now-playing-0.6.0/node_modules/node-notifier/vendor/terminal-notifier.app/Contents` and changing the `<string>alert</string>` to `<string>banner</string>`.

Since this file and the folders containing it are all generated after executing `yarn install`,  I can't just make a pull request changing this `<string>` value to the proper one. Do you know if there's a way to force the desired setting through Electron so when `yarn install` is executed (maybe by adding something to `package.json`)?

**Comment by davicorreiajr** [comment]
Maybe I didn't understand correctly, but if I got it right, you want to make in a way that the notification is always a banner, right?

I don't know if I like this, because we'd be overwriting the user's preference. For example, for me, since the first time you opened that pull request, it worked like a banner (I had to go to the preferences and changed it to see what you were talking about.

Anyway, what do you think? In summary, I don't like the idea of overwrite some system pref.

**Comment by davicorreiajr** [comment]
hey, first of all, sorry for taking so long to answer.

What I found weird is that I never had to change from Alerts to Banners, it's been like Banners for me since the first time you implemented this. I agree with that the Alerts would be quite annoying, but I didn't understand yet why the default for me was a Banner and for you an Alert. I uninstalled and installed the app again, and it keeps to work as a Banner.

About the code change, [there're ways](https://medium.com/@chrisdmasters/how-to-fork-a-dependency-and-use-it-locally-in-a-project-707c80d3449c) to solve the problem (when you need to change a package), but I'm not sure if it's worth it. The timeout seems easier. Do you know if the timeout works for both Alert and Banner cases?

**Comment by bressan3** [comment]
I completely agree with you and don't think it's worth it to change the package. And yes, the timeout is supposed to work with both Alerts and Banners.

**Comment by davicorreiajr** [comment]
Fixed with #27
