### ISSUE TITLE
'Spotify-now playing quit unexpectedly'

### ISSUE THREAD

**Issue by joaogolias** [davicorreiajr/spotify-now-playing#4]
## What are you reporting?

* [X] Bug, or some problem;

## In which context are you running the app?
I running the app in a MacBook Air, Majove, version 10.14.1

## Description
I was using other programs in my computer, and, suddenly, I got the following error: 'Spotify-now playing quit unexpectedly'. 
As it had already quit, I could not see the report in Activity Monitor, but I guess it is related to the quantity of requests that your app does. In the moment it happened, I was using chrome with a lot of tabs and running two backend projects. 

The error file is attached to this issue! 

[error-28-11-2018.txt](https://github.com/davicorreiajr/spotify-now-playing/files/2624837/error-28-11-2018.txt)

**Comment by davicorreiajr** [comment]
Hello Golias,

I just release a new version: https://github.com/davicorreiajr/spotify-now-playing/releases/tag/v0.2.1

Since I couldn't find the exact problem, it's hard to be 100% sure. But I think there was some problems with unhandled promises and with events listeners. I believe that this version solves the problem; if not, please let me know.
