### ISSUE TITLE
Better icon for status bar

### ISSUE THREAD

**Issue by GLaDO8** [davicorreiajr/spotify-now-playing#8]
## What are you reporting?
* [X] Improvement in an existing feature

## In which context are you running the app?
macOS 10.14.1 and app version 0.2.0

## Description
The current icon in the status bar is pixelated. We could possibly replace the png with an SVG?

**Comment by davicorreiajr** [comment]
Hello, thanks for your report!

I just released a new version: https://github.com/davicorreiajr/spotify-now-playing/releases/tag/v0.2.1.

Since I don't have a retina display, it's hard for me to be sure, but I think it's fixed so I'm gonna close the issue. If this still doesn't solve the problem, please let me know!
